{"version":3,"sources":["components/ErrorBoundary/ErrorBoundary.jsx"],"names":["ErrorBoundary","state","hasError","children","this","props","error","Component"],"mappings":"2KAEMA,E,4MACJC,MAAQ,CAAEC,UAAU,G,uDAUV,IACAC,EAAaC,KAAKC,MAAlBF,SACR,OAAIC,KAAKH,MAAMC,SACN,+HAEFC,K,gDATuBG,GAC9B,MAAO,CAAEJ,UAAU,O,GARKK,aAoBbP","file":"static/js/components-ErrorBoundary-ErrorBoundary.807715dc.chunk.js","sourcesContent":["import React, { Component } from \"react\";\n\nclass ErrorBoundary extends Component {\n  state = { hasError: false };\n\n  // componentDidCatch(error, info) {\n  //   this.setState({ hasError: true });\n  // }\n\n  static getDerivedStateFromError(error) {\n    return { hasError: true };\n  }\n\n  render() {\n    const { children } = this.props;\n    if (this.state.hasError) {\n      return <div>Что-то пошло не так</div>;\n    }\n    return children;\n  }\n}\n\nexport default ErrorBoundary;\n"],"sourceRoot":""}